from __future__ import annotations

from pathlib import Path

import typer

from scout.core.models import ScanConfig

app = typer.Typer(help="Project initialization commands.")


REPO_RULES_YAML = """\
metadata:
  name: "repo-overrides"
  version: "1"
  description: "Repo-specific overrides for secret-scout. Builtin rules always run; this file can override/extend them."

rules:
  # Example: downgrade env-file filename finding severity (override by same id)
  # - id: "filename.env-files"
  #   type: "filename"
  #   severity: "medium"
  #   description: "Downgraded for this repo; we still want to catch real secrets via regex/structured rules."
  #   tags: ["env", "filename"]
  #   filename:
  #     pattern_type: "regex"
  #     pattern: "(^|/)\\\\.env($|\\\\.)|(^|/).*\\\\.env$|(^|/)env\\\\..+"
  #   allow_paths:
  #     - "**/.env.example"
  #     - "**/.env.template"
  #     - "**/.env.sample"
  #     - "**/.env.dist"
"""


STRICT_RULES_HINT_YAML = """\
metadata:
  name: "repo-overrides"
  version: "1"
  description: "Repo-specific overrides for secret-scout (strict mode starter)."

rules:
  # Tip: start by adding allowlists to reduce false positives, then tighten over time.
  # Example allowlist:
  # - id: "regex.generic-secret-assignments"
  #   type: "regex"
  #   severity: "high"
  #   description: "Stricter default for generic secret assignment detection."
  #   tags: ["generic", "content"]
  #   regex:
  #     regex: "\\\\b(api[_-]?key|secret|token|password|passwd|pwd)\\\\b\\\\s*[:=]\\\\s*['\\\\\\\"]?.{8,}['\\\\\\\"]?"
  #     scope: "line"
  #     max_matches: 5
"""


DEFAULT_GITIGNORE = """\
# secret-scout local artifacts
.secret-scout/.cache/
.secret-scout/cache/
.secret-scout/tmp/

# Baselines (optional: commit if you want)
.secret-scout/baseline.json
.secret-scout/baseline*.json
"""


DEFAULT_README = """\
# secret-scout configuration

This repo uses `secret-scout` to prevent accidental commits of secrets (.env files, private keys, tokens, etc.)

## Files

- `config.toml` — scan behavior (max file size, skip dirs, redact)
- `rules.yaml` — repo-specific policy overrides and custom rules

## Typical usage

Local:
```bash
secret-scout scan-path .
```

CI:
```bash
secret-scout scan-path . --fail
```

## Notes
- Built-in rule pack is always loaded (default). rules.yaml can override by reusing the same id.
- Keep redact=true in CI to avoid printing secrets in logs.
"""


def _bool(v: bool) -> str:
    return "true" if v else "false"


def render_default_config_toml() -> str:
    """
    Render .secret-scout/config.toml from ScanConfig defaults to avoid drift.
    """
    cfg = ScanConfig()
    d = cfg.model_dump()

    lines: list[str] = []
    lines.append("[scan]")
    lines.append("# Generated by `secret-scout init` from ScanConfig defaults.")
    lines.append("")
    lines.append(f"max_file_bytes = {int(d['max_file_bytes'])}")
    lines.append(f"redact = {_bool(bool(d['redact']))}")
    lines.append(f"include_ignored = {_bool(bool(d['include_ignored']))}")
    lines.append(f"deterministic = {_bool(bool(d['deterministic']))}")
    lines.append("")
    lines.append("skip_dirs = [")
    for name in d.get("skip_dirs", []):
        lines.append(f'  "{name}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def _write_file(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        raise typer.BadParameter(
            f"File already exists: {path} (use --force to overwrite)"
        )
    path.write_text(content, encoding="utf-8")


@app.command("init")
def init_cmd(
    directory: Path = typer.Argument(
        Path("."),
        exists=True,
        file_okay=False,
        dir_okay=True,
        readable=True,
        help="Target directory (repo root) where .secret-scout/ will be created.",
    ),
    force: bool = typer.Option(
        False, "--force", help="Overwrite existing files if present."
    ),
    strict: bool = typer.Option(
        False, "--strict", help="Generate a stricter starter rules.yaml template."
    ),
    no_gitignore: bool = typer.Option(
        False, "--no-gitignore", help="Do not create .secret-scout/.gitignore"
    ),
    no_readme: bool = typer.Option(
        False, "--no-readme", help="Do not create .secret-scout/README.md"
    ),
) -> None:
    root = directory.resolve()
    cfg_dir = root / ".secret-scout"
    cfg_dir.mkdir(parents=True, exist_ok=True)

    _write_file(cfg_dir / "config.toml", render_default_config_toml(), force=force)
    _write_file(
        cfg_dir / "rules.yaml",
        (STRICT_RULES_HINT_YAML if strict else REPO_RULES_YAML),
        force=force,
    )

    if not no_gitignore:
        _write_file(cfg_dir / ".gitignore", DEFAULT_GITIGNORE, force=force)

    if not no_readme:
        _write_file(cfg_dir / "README.md", DEFAULT_README, force=force)

    typer.echo(f"✅ Initialized secret-scout config in: {cfg_dir}")
